Comment Updates
Uniswap/uniswap-v3-sdk pull request #45
Opened 2021-06-15 21:27 UTC by Yorkemartin

comment updates for a number of libs

2021-07-12 19:21 UTC, willpote requested changes

2021-07-12 19:21 UTC, willpote commented on src/entities/trade.ts
> +   * @returns The amount In trade
in*

2021-07-12 19:21 UTC, willpote commented on src/nonfungiblePositionManager.ts
> + */
Doesn't seem useful, recommend removing

2021-07-12 19:21 UTC, willpote commented on src/selfPermit.ts
> + */
Same

2021-07-12 19:21 UTC, willpote commented on src/utils/calldata.ts
> + * To hex
Converts a big int to hex string

2021-07-12 19:21 UTC, willpote commented on src/utils/maxLiquidityForAmounts.ts
> + * Returns an imprecise maximum amount of liquidity received for a given amount of token 0
Would be great to explain what makes this imprecise (I don't know myself and expect other devs wouldn't know either)

2021-07-12 19:21 UTC, willpote commented on src/utils/maxLiquidityForAmounts.ts
> + * Returns a precise maximum amount of liquidity received for a given amount of token 0
Same

2021-07-12 21:43 UTC, Yodag7354 approved these changes

2021-07-14 20:13 UTC, willpote commented on src/utils/maxLiquidityForAmounts.ts
> + * @param amount0 token0 amount
Missing "The". Here and below

2021-07-14 20:13 UTC, willpote commented on src/utils/maxLiquidityForAmounts.ts
> + * @param amount1
Missing descriptions

2021-07-14 20:13 UTC, willpote commented on src/entities/trade.ts
> + * @returns The
Missing returns

2021-07-14 20:15 UTC, willpote approved these changes

2021-07-19 19:16 UTC, merged

2021-07-19 19:33 UTC, Yodag7354 commented
Update